// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('app').config(function($stateProvider) {
    return $stateProvider.state('app', {
      url: '/app',
      abstract: true,
      templateUrl: 'js/layout/menu.html',
      controller: 'MenuCtrl',
      data: {
        restrictAccess: ['logged']
      }
    });
  }).controller('MenuCtrl', function($scope, $state, AuthSrv) {
    var logout, vm;
    vm = {};
    logout = function() {
      return AuthSrv.logout().then(function() {
        return $state.go('login');
      });
    };
    $scope.vm = vm;
    return vm.logout = logout;
  });

}).call(this);

//# sourceMappingURL=menu.js.map
