// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('app').config(function($stateProvider) {
    return $stateProvider.state('login', {
      url: '/login',
      templateUrl: 'js/authentication/login.html',
      controller: 'LoginController',
      data: {
        restrictAccess: ['notLogged']
      }
    });
  }).controller('LoginController', function($scope, $state, AuthSrv) {
    var login, vm;
    vm = {};
    login = function(credentials) {
      vm.error = null;
      vm.loading = true;
      return AuthSrv.login(credentials).then(function() {
        $state.go('app.search');
        vm.credentials.password = '';
        vm.error = null;
        return vm.loading = false;
      }, function(error) {
        vm.credentials.password = '';
        vm.error = error.data && error.data.message ? error.data.message : error.statusText;
        return vm.loading = false;
      });
    };
    $scope.vm = vm;
    vm.error = null;
    vm.loding = false;
    vm.credentials = {
      login: '',
      password: ''
    };
    return vm.login = login;
  });

}).call(this);

//# sourceMappingURL=login.js.map
