// Generated by CoffeeScript 1.9.3
(function() {
  var UserSrv;

  angular.module('app').factory('UserSrv', UserSrv);

  UserSrv.$inject = ['StorageUtils'];

  UserSrv = function(StorageUtils) {
    var deleteCurrentUser, getCurrentUser, service, setCurrentUser, userKey;
    userKey = 'user';
    service = {
      storageKey: userKey,
      get: getCurrentUser,
      set: setCurrentUser,
      "delete": deleteCurrentUser
    };
    getCurrentUser = function() {
      return StorageUtils.get(userKey);
    };
    setCurrentUser = function(user) {
      return StorageUtils.set(userKey, user);
    };
    deleteCurrentUser = function() {
      return StorageUtils.clear(userKey);
    };
    return service;
  };

}).call(this);

//# sourceMappingURL=user.srv.js.map
