// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('app').config(function($stateProvider) {
    return $stateProvider.state('app.search', {
      url: '/search',
      templateUrl: 'js/search/search.html',
      controller: 'SearchController'
    });
  }).controller('SearchController', function($scope) {
    var vm;
    vm = {};
    return $scope.vm = vm;
  });

}).call(this);

//# sourceMappingURL=search.js.map
