// Generated by CoffeeScript 1.9.3
(function() {
  var DataUtils;

  angular.module('app').factory('DataUtils', DataUtils);

  DataUtils.$inject = ['$http', 'StorageUtils', 'Config'];

  DataUtils = function($http, StorageUtils, Config) {
    var getOrFetch, refresh, service;
    service = {
      getOrFetch: getOrFetch,
      refresh: refresh
    };
    getOrFetch = function(storageKey, url, _absolute) {
      return StorageUtils.get(storageKey).then(function(data) {
        if (data) {
          return data;
        } else {
          return refresh(storageKey, url, _absolute);
        }
      });
    };
    refresh = function(storageKey, url, _absolute) {
      return $http.get(_absolute ? url : Config.backendUrl + url).then(function(res) {
        return StorageUtils.set(storageKey, res.data).then(function() {
          return res.data;
        });
      });
    };
    return service;
  };

}).call(this);

//# sourceMappingURL=data-utils.js.map
