// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('app').factory('customLogger', function() {
    var track;
    track = function(name, data, _time) {
      var event;
      if (typeof data === 'string') {
        data = {
          message: data
        };
      }
      event = {};
      if (data) {
        event.data = data;
      }
      if (_time) {
        event.time = _time;
      }
      return Logger.track(name, event);
    };
    return function($delegate) {
      return {
        debug: function() {
          return $delegate.debug.apply(null, arguments);
        },
        log: function() {
          track(arguments[0], arguments[1], arguments[2]);
          return $delegate.log.apply(null, arguments);
        },
        info: function() {
          return $delegate.info.apply(null, arguments);
        },
        warn: function() {
          return $delegate.warn.apply(null, arguments);
        },
        error: function() {
          var cause, data, exception;
          if (typeof arguments[0] === 'string') {
            track('error', {
              type: arguments[0],
              error: arguments[1]
            }, arguments[2]);
          } else {
            exception = arguments[0];
            cause = arguments[1];
            data = {
              type: 'angular'
            };
            if (cause) {
              data.cause = cause;
            }
            if (exception) {
              if (exception.message) {
                data.message = exception.message;
              }
              if (exception.name) {
                data.name = exception.name;
              }
              if (exception.stack) {
                data.stack = exception.stack;
              }
            }
            track('exception', data);
          }
          return $delegate.error.apply(null, arguments);
        }
      };
    };
  });

}).call(this);

//# sourceMappingURL=logger.js.map
