// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('app').factory('CameraPlugin', function($window, $q, $log, PluginUtils) {
    var _getPicture, defaultOpts, findPicture, pluginName, pluginTest, service, takePicture;
    pluginName = 'Camera';
    pluginTest = function() {
      return $window.navigator && $window.navigator.camera;
    };
    service = {
      getPicture: _getPicture,
      takePicture: takePicture,
      findPicture: findPicture
    };
    defaultOpts = {
      quality: 75,
      destinationType: $window.Camera.DestinationType.FILE_URI,
      sourceType: $window.Camera.PictureSourceType.CAMERA,
      allowEdit: false,
      encodingType: $window.Camera.EncodingType.JPEG,
      mediaType: $window.Camera.MediaType.PICTURE,
      cameraDirection: $window.Camera.Direction.BACK,
      correctOrientation: true,
      saveToPhotoAlbum: false
    };
    _getPicture = function(_opts) {
      return PluginUtils.onReady(pluginName, pluginTest).then(function() {
        var defer, opts;
        opts = angular.extend(defaultOpts, _opts);
        defer = $q.defer();
        $window.navigator.camera.getPicture((function(picture) {
          return defer.resolve(picture);
        }), (function(error) {
          $log.error('pluginError:' + pluginName, error);
          return defer.reject(error);
        }), opts);
        return defer.promise;
      });
    };
    takePicture = function() {
      return _getPicture({});
    };
    findPicture = function() {
      return _getPicture({
        sourceType: $window.Camera.PictureSourceType.PHOTOLIBRARY
      });
    };
    return service;
  });


  /**************************
   *                        *
   *      Browser Mock      *
   *                        *
  #************************
   */

  ionic.Platform.ready(function() {
    if (!(ionic.Platform.isAndroid() || ionic.Platform.isIOS() || ionic.Platform.isIPad())) {
      if (!window.navigator) {
        window.navigator = {};
      }
      if (!window.navigator.camera) {
        return window.navigator.camera = (function() {
          var ret;
          window.Camera = {
            DestinationType: {
              DATA_URL: 0,
              FILE_URI: 1,
              NATIVE_URI: 2
            },
            Direction: {
              BACK: 0,
              FRONT: 1
            },
            EncodingType: {
              JPEG: 0,
              PNG: 1
            },
            MediaType: {
              PICTURE: 0,
              VIDEO: 1,
              ALLMEDIA: 2
            },
            PictureSourceType: {
              PHOTOLIBRARY: 0,
              CAMERA: 1,
              SAVEDPHOTOALBUM: 2
            },
            PopoverArrowDirection: {
              ARROW_UP: 1,
              ARROW_DOWN: 2,
              ARROW_LEFT: 4,
              ARROW_RIGHT: 8,
              ARROW_ANY: 15
            }
          };
          ret = JSON.parse(JSON.stringify(window.Camera));
          ret.getPicture = function(success, error, options) {
            var uri;
            uri = window.prompt('Image uri :');
            if (uri) {
              if (success) {
                success(uri);
              }
            } else {
              if (error) {
                error();
              }
            }
          };
          return ret;
        })();
      }
    }
  });

}).call(this);

//# sourceMappingURL=camera.js.map
