// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('app').factory('DevicePlugin', function($window, PluginUtils) {
    var getDevice, getDeviceUuid, pluginName, pluginTest, service;
    pluginName = 'Device';
    pluginTest = function() {
      return $window.device;
    };
    service = {
      getDevice: getDevice,
      getDeviceUuid: getDeviceUuid
    };
    getDevice = function() {
      return PluginUtils.onReady(pluginName, pluginTest).then(function() {
        return $window.device;
      });
    };
    getDeviceUuid = function() {
      return getDevice().then(function(device) {
        return device.uuid;
      });
    };
    return service;
  });


  /**************************
   *                        *
   *      Browser Mock      *
   *                        *
  #************************
   */

  ionic.Platform.ready(function() {
    var android, browser;
    if (!(ionic.Platform.isAndroid() || ionic.Platform.isIOS() || ionic.Platform.isIPad())) {
      if (!window.device) {
        browser = {
          available: true,
          cordova: '',
          manufacturer: '',
          model: '',
          platform: 'browser',
          uuid: '0123456789',
          version: '0'
        };
        android = {
          available: true,
          cordova: '3.6.4',
          manufacturer: 'LGE',
          model: 'Nexus 4',
          platform: 'Android',
          uuid: '891b8e516ae6bd65',
          version: '5.0.1'
        };
        return window.device = browser;
      }
    }
  });

}).call(this);

//# sourceMappingURL=device.js.map
