// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('app').factory('SocialSharingPlugin', function($window, $q, $log, PluginUtils) {
    var pluginName, pluginTest, service, share, shareViaEmail, shareViaFacebook, shareViaTwitter;
    pluginName = 'SocialSharing';
    pluginTest = function() {
      return $window.plugins && $window.plugins.socialsharing;
    };
    service = {
      share: share,
      shareViaFacebook: shareViaFacebook,
      shareViaTwitter: shareViaTwitter,
      shareViaEmail: shareViaEmail
    };
    share = function(message, _subject, _fileOrFileArray, _link) {
      return PluginUtils.onReady(pluginName, pluginTest).then(function() {
        var defer;
        defer = $q.defer();
        $window.plugins.socialsharing.share(message, _subject || null, _fileOrFileArray || null, _link || null, (function() {
          return defer.resolve();
        }), function(error) {
          $log.error('pluginError:' + pluginName, error);
          return defer.reject(error);
        });
        return defer.promise;
      });
    };
    shareViaFacebook = function(message, _fileOrFileArray, _link) {
      return PluginUtils.onReady(pluginName, pluginTest).then(function() {
        var defer;
        defer = $q.defer();
        $window.plugins.socialsharing.shareViaFacebookWithPasteMessageHint(message, _fileOrFileArray || null, _link || null, 'Tu peux coller le message par défaut si tu veux...', (function() {
          return defer.resolve();
        }), function(error) {
          $log.error('pluginError:' + pluginName, error);
          return defer.reject(error);
        });
        return defer.promise;
      });
    };
    shareViaTwitter = function(message, _file, _link) {
      return PluginUtils.onReady(pluginName, pluginTest).then(function() {
        var defer;
        defer = $q.defer();
        $window.plugins.socialsharing.shareViaTwitter(message, _file || null, _link || null, (function() {
          return defer.resolve();
        }), function(error) {
          $log.error('pluginError:' + pluginName, error);
          return defer.reject(error);
        });
        return defer.promise;
      });
    };
    shareViaEmail = function(message, _subject, _fileOrFileArray) {
      return PluginUtils.onReady(pluginName, pluginTest).then(function() {
        var defer;
        defer = $q.defer();
        $window.plugins.socialsharing.shareViaEmail(message, _subject || null, null, null, null, _fileOrFileArray || null, (function() {
          return defer.resolve();
        }), function(error) {
          $log.error('pluginError:' + pluginName, error);
          return defer.reject(error);
        });
        return defer.promise;
      });
    };
    return service;
  });


  /**************************
   *                        *
   *      Browser Mock      *
   *                        *
  #************************
   */

  ionic.Platform.ready(function() {
    if (!(ionic.Platform.isAndroid() || ionic.Platform.isIOS() || ionic.Platform.isIPad())) {

    } else {

    }
  });

}).call(this);

//# sourceMappingURL=social-sharing.js.map
