// Generated by CoffeeScript 1.9.3
(function() {
  var ToastPlugin;

  ToastPlugin = function($window, PluginUtils) {
    var pluginName, pluginTest, service, show;
    pluginName = 'Toast';
    pluginTest = function() {
      return $window.plugins && $window.plugins.toast;
    };
    service = {
      show: show,
      showShortTop: function(message, successCb, errorCb) {
        return show(message, 'short', 'top', successCb, errorCb);
      },
      showShortCenter: function(message, successCb, errorCb) {
        return show(message, 'short', 'center', successCb, errorCb);
      },
      showShortBottom: function(message, successCb, errorCb) {
        return show(message, 'short', 'bottom', successCb, errorCb);
      },
      showLongTop: function(message, successCb, errorCb) {
        return show(message, 'long', 'top', successCb, errorCb);
      },
      showLongCenter: function(message, successCb, errorCb) {
        return show(message, 'long', 'center', successCb, errorCb);
      },
      showLongBottom: function(message, successCb, errorCb) {
        return show(message, 'long', 'bottom', successCb, errorCb);
      }
    };
    show = function(message, duration, position, successCb, errorCb) {
      if (!duration) {
        duration = 'short';
      }
      if (!position) {
        position = 'bottom';
      }
      if (!successCb) {
        successCb = function(status) {};
      }
      if (!errorCb) {
        errorCb = function(error) {};
      }
      return PluginUtils.onReady(pluginName, pluginTest).then(function() {
        return $window.plugins.toast.show(message, duration, position, successCb, errorCb);
      });
    };
    return service;
  };

  'use strict';

  angular.module('app').factory('ToastPlugin', ToastPlugin);


  /**************************
   *                        *
   *      Browser Mock      *
   *                        *
  #************************
   */

  ionic.Platform.ready(function() {
    if (!(ionic.Platform.isAndroid() || ionic.Platform.isIOS() || ionic.Platform.isIPad())) {
      if (!window.plugins) {
        window.plugins = {};
      }
      if (!window.plugins.toast) {
        return window.plugins.toast = {
          show: function(message, duration, position, successCallback, errorCallback) {
            console.log('Toast: ' + message);
            if (successCallback) {
              return window.setTimeout(successCallback('OK'), 0);
            }
          },
          showShortTop: function(message, successCallback, errorCallback) {
            return this.show(message, 'short', 'top', successCallback, errorCallback);
          },
          showShortCenter: function(message, successCallback, errorCallback) {
            return this.show(message, 'short', 'center', successCallback, errorCallback);
          },
          showShortBottom: function(message, successCallback, errorCallback) {
            return this.show(message, 'short', 'bottom', successCallback, errorCallback);
          },
          showLongTop: function(message, successCallback, errorCallback) {
            return this.show(message, 'long', 'top', successCallback, errorCallback);
          },
          showLongCenter: function(message, successCallback, errorCallback) {
            return this.show(message, 'long', 'center', successCallback, errorCallback);
          },
          showLongBottom: function(message, successCallback, errorCallback) {
            return this.show(message, 'long', 'bottom', successCallback, errorCallback);
          }
        };
      }
    }
  });

}).call(this);

//# sourceMappingURL=toast.js.map
