// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('app').factory('PluginUtils', function($window, $ionicPlatform, $q, $log) {
    var onReady, service;
    service = {
      onReady: onReady
    };
    onReady = function(name, testFn) {
      return $ionicPlatform.ready().then(function() {
        if (!testFn()) {
          $log.error('pluginNotFound:' + name);
          return $q.reject({
            message: 'pluginNotFound:' + name
          });
        }
      });
    };
    return service;
  });

}).call(this);

//# sourceMappingURL=utils.js.map
