// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('app').config(function($stateProvider) {
    return $stateProvider.state('app.charts', {
      url: '/charts',
      templateUrl: 'js/charts/charts.html',
      controller: 'ChartsController'
    });
  }).controller('ChartsController', function($scope) {
    var vm;
    vm = {};
    return $scope.vm = vm;
  });

}).call(this);

//# sourceMappingURL=charts.js.map
